### ISSUE TITLE
Confusion about details of downsampling

### ISSUE THREAD

**Issue by VictorYrotciV** [zhuoxiao-chen/ReDB-DA-3Ddet#2]
Hi, your excellent work has brought me great inspiration. After looking through your paper, I wonder how you perform downsampling in stage 2 in detail. I mean that if we want to "uniformly downsample" a set of pseudo labels to obtain a subset with a length of \hat{B}/t, we can just randomly choose \hat{B}/t box predictions from the original box prediction set, then what does inverse KDE do in this process? Or “uniform downsampling" is just a proper noun of 3d detection? 

Thanks for your reply in advance.

**Comment by zhuoxiao-chen** [comment]
Hi, 

Appreciate your time in reading our work.

We are **randomly** choosing box predictions but **guided by the probability estimated by KDE**. Objects with higher OBCs values are assigned higher probablity to be chosen.

I will delve into OBC-based downsampling from two perspectives:

1. Why? Higher OBC scores signify the rarity, diversity, and uniqueness of predicted objects. In reality, most objects are common and occur frequently, thus producing lower OBC scores. We aim for the detector to learn from a varied set of pseudo-labeled objects, not biased to the majority common objects with low OBCs. Hence, we require pseudo-labels with uniformly distributed OBC scores, leading us to uniformly downsample based on OBC scores across all box predictions.
2. How? Initially, we estimate the OBC score distribution of all box predictions via Kernel Density Estimation (KDE). The density of low OBC scores is notably high (due to large number of common objects), while that of high OBC scores is low. By inverting this distribution, we the density of high OBC scores becomes high. This altered distribution allows us to assign higher probabilities to pseudo-labeled objects with inversed OBC distribution. As a result, the downsampled set contains pseudo-labeled objects with more evenly distributed OBC scores.

<img width="400" alt="image" src="https://github.com/zhuoxiao-chen/ReDB-DA-3Ddet/assets/50613939/279583a8-5245-4b98-87b9-809ba6c5bf51">


I hope this addresses your question.

Regards,
Zhuoxiao (Ivan)

**Comment by VictorYrotciV** [comment]
I got it. Thanks for your prompt reply!
